# Project info
site_name: Postgres by Tealbase
site_description: >-
   Provide some of the most common Postgres extensions with a one-click install.

# Repository
repo_name: tealbase/postgres
repo_url: https://github.com/tealbase/postgres

nav:
  - Home: README.md
  - Development:
    - Getting Started: start-here.md
    - Nix tree structure: nix-directory-structure.md
    - Workflow: development-workflow.md
    - Build PostgreSQL: build-postgres.md
    - Start Client/Server: start-client-server.md
    - Docker: docker.md
    - Use direnv: use-direnv.md
    - Code Formatter: nix-formatter.md
    - Pre-commit Hooks: pre-commit-hooks.md
    - Documentation: documentation.md
  - Package Management:
    - Adding New Packages: adding-new-package.md
    - Update Extensions: update-extension.md
    - New Major PostgreSQL: new-major-postgres.md
    - Nix Overlays: nix-overlays.md
  - Testing:
    - Adding Tests: adding-tests.md
    - Migration Tests: migration-tests.md
    - Testing PG Upgrade Scripts: testing-pg-upgrade-scripts.md
  - References: references.md

validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn

# Configuration

docs_dir: docs
site_dir: out

theme:
    name: material

    logo: assets/images/logo.png
    favicon: assets/images/logo.png

    features:
        - content.code.annotate
        - content.code.copy
        - navigation.footer
        - navigation.indexes
        - navigation.path
        - navigation.sections
        - navigation.tabs
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest

    font:
        text: Inter
        mono: Noto Sans Mono
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

extra:
    version:
        provider: mike
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/tealbase/postgres

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - tables
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - def_list
    - meta
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.highlight:
          use_pygments: true
          linenums: true
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
          base_path: ../.
    - pymdownx.keys
    - pymdownx.superfences:
          # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
    - mike
    - search
    - mermaid2
