# Downloading dependencies
- name: Postgres dependencies
  become: yes
  apt:
    pkg:
      - liblzo2-dev
      - cmake

# install go dependency for WAL-G
- name: wal-g go dependency
  get_url:
    url: "https://golang.org/dl/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /tmp

- name: unpack go archive
  unarchive:
    remote_src: yes
    src: "/tmp/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /usr/local

# Download WAL-G
- name: download wal-g
  shell:
    cmd: go get github.com/wal-g/wal-g;
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  ignore_errors: yes
  # ignore error https://github.com/wal-g/wal-g/issues/343#issuecomment-514544288

# Install WAL-G
- name: install wal-g
  become: yes
  shell:
    cmd: make install && make deps && make pg_install
    chdir: "{{ ansible_env.HOME }}/go/src/github.com/wal-g/wal-g"
  environment:
    GOBIN: "/usr/local/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

# Clean up Go
- name: Uninstall Go
  become: yes
  file:
    path: /usr/local/go
    state: absent  